name: hotelorg
description: "A new Flutter project."

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
<<<<<<< HEAD
  dio: ^5.3.2
=======
  qr_flutter: ^4.1.0
  uni_links: ^0.5.1
>>>>>>> f23a634d54831f50520de900e73a5386b850ae21

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.3.0  

 
  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true


 
